GET http://localhost:3001/api/blogs

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": "04"
}

###
PUT http://localhost:3003/api/blogs/65d1a7efe30bd971eb7d16d5
Content-Type: application/json

{
    "title": "frontTitle",
    "author": "frontAuthor",
    "url": "frontUrl",
    "likes": 1000
}

###
Delete http://localhost:3003/api/blogs/65d05c6c714e054d8f48fea9

// missing
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test"
}
